### ISSUE TITLE
How to detect device type (As printer)

### ISSUE THREAD

**Issue by minhthuc251** [mavris/MMLanScan#2]
I need to detect printer connected in network . Can i do it with your library ?
It will be perfect with me with this fuction.I really need it

**Comment by mavris** [comment]
That would be nice addition. We can do it but we need a database of MAC Addresses and the kind of devices. For example in order to find the Brand of a specific device we had a dictionary that holds MAC Addresses and Brands. We need the database for the kind of the device. I did some search but with no luck. If you find any kind of data that we could use let me know

**Comment by minhthuc251** [comment]
Thanks for your help. I will contact you if i find somethingelse
